apiVersion: v1
kind: Pod
metadata:
  name: carla-client-dev
  namespace: seelab
  labels:
    app: carla-client-dev
spec:
  restartPolicy: Never

  tolerations:
    - key: "nautilus.io/issue"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "nautilus.io/testing"
      operator: "Exists"
      effect: "NoSchedule"

  containers:
  - name: client
    image: vllm/vllm-openai:latest
    command: ["/bin/bash", "-lc"]
    args:
      - |
        set -e

        echo "[INFO] Installing basic utilities..."
        apt-get update && apt-get install -y \
          vim \
          procps \
          htop \
          curl \
          wget \
          iproute2 \
          net-tools \
          less \
          tmux \
          git \
          && rm -rf /var/lib/apt/lists/*

        # Put HF cache on your PVC so the model download persists across pod restarts.
        export HF_HOME=/workspace/.cache/huggingface
        export TRANSFORMERS_CACHE=/workspace/.cache/huggingface
        export HF_HUB_DISABLE_TELEMETRY=1

        mkdir -p /workspace/.cache/huggingface

        pip3 install carla==0.9.16 

        # Start OpenAI-compatible server on port 8000
        vllm serve Qwen/Qwen2.5-VL-3B-Instruct-AWQ \
          --host 0.0.0.0 \
          --port 8000 \
          --gpu-memory-utilization 0.75 \
          --max-model-len 2048 \
          --max-num-seqs 1 \
          --mm-encoder-tp-mode data \
          --limit-mm-per-prompt '{"image":1,"video":0}'


    ports:
      - containerPort: 8000
        name: http

    resources:
      requests:
        cpu: "2"
        memory: "32Gi"
        nvidia.com/gpu: 1
      limits:
        cpu: "4"
        memory: "32Gi"
        nvidia.com/gpu: 1

    volumeMounts:
    - name: storage
      mountPath: /workspace

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: bgupta-pvc